return {
  ACTIVE = 'active',
  ASSET_PATH_ARTIFACT_DEFAULT = '/home/we/dust/code/esper/assets/test/',
  ASSET_PATH_ARTIFACT_USER = '/home/we/dust/data/esper/assets/',
  ASSET_PATH_UI = '/home/we/dust/code/esper/assets/ui/',
  BEAT = 'beat_',
  CURRENT = 'current',
  COLUMNS = 8,
  DIRTY_CLOCK = 'dirty_clock',
  DIRTY_SCALE = 'dirty_scale',
  FORWARD = 'forward_',
  GLYPH_PATH = 'glyphs/',
  INACTIVE = 'inactive',
  MEDIAN = 'median',
  MEAN = 'mean',
  MODE = 'mode',
  PLAY = 'play_',
  POWER = 'power',
  REGION = 'region',
  REVERSE = 'reverse_',
  ROWS = 8,
  SELECTED = 'selected',
  SHIFT = 'shift',
  STOP = 'stop_',
  X = 'x',
  Y = 'y'
}